name: Deploy to EKS

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: cluster
  ECR_FRONTEND: 005119769001.dkr.ecr.us-east-1.amazonaws.com/frontend
  ECR_BACKEND: 005119769001.dkr.ecr.us-east-1.amazonaws.com/backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Frontend Image
        run: |
          docker build -t $ECR_FRONTEND:${{ github.sha }} -t $ECR_FRONTEND:latest ./starter/frontend
          docker push $ECR_FRONTEND:${{ github.sha }}
          docker push $ECR_FRONTEND:latest

      - name: Build & Push Backend Image
        run: |
          docker build -t $ECR_BACKEND:${{ github.sha }} -t $ECR_BACKEND:latest ./starter/backend
          docker push $ECR_BACKEND:${{ github.sha }}
          docker push $ECR_BACKEND:latest

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy Kubernetes Manifests
        run: |
          kubectl apply -f .
